# Generated by Django 2.2.1 on 2019-06-09 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='kategoria')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=250, verbose_name='opis')),
                ('position', models.IntegerField(blank=True, default=0, null=True, verbose_name='pozycja')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Category', verbose_name='kategoria główna')),
            ],
            options={
                'verbose_name': 'kategoria',
                'verbose_name_plural': 'kategorie',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nazwa tematu')),
                ('slug', models.SlugField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='utworzony')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'aktywny'), ('blocked', 'zablokowany'), ('reported', 'zgłoszony'), ('hidden', 'ukryty')], default='active', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Category', verbose_name='kategoria')),
            ],
            options={
                'verbose_name': 'temat',
                'verbose_name_plural': 'tematy',
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='tekst')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='utworzony')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'aktywny'), ('reported', 'zgłoszony'), ('hidden', 'ukryty'), ('delete', 'usunięty')], default='active', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Topic', verbose_name='temat')),
            ],
            options={
                'verbose_name': 'odpowiedź',
                'verbose_name_plural': 'odpowiedzi',
            },
        ),
    ]
